USE [QLTV]
GO

/****** Object:  Table [dbo].[HOCVIEN_IMG]    Script Date: 05/25/2016 22:15:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HOCVIEN_IMG](
	[IMG_ID] [int] IDENTITY(1,1) NOT NULL,
	[IMG_HOVID] [int] NOT NULL,
	[IMG_Name] [nvarchar](100) NULL,
	[IMG_Image] [image] NULL,
 CONSTRAINT [PK_HOCVIEN_IMG] PRIMARY KEY CLUSTERED 
(
	[IMG_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


